In [5]:
from movielens_dataset import MovieLens

In [4]:
import movielens_dataset
reload(movielens_dataset)

In [6]:
dataset = MovieLens()

In [7]:
df = dataset.get_user_like_list()

In [21]:
df.apply(lambda x: x.movieId.tolist())

userId
1         [151, 223, 253, 260, 293, 296, 318, 541, 1036,...
2         [3, 62, 70, 110, 260, 266, 480, 541, 589, 908,...
3         [1, 32, 50, 175, 223, 260, 316, 318, 329, 457,...
4         [10, 350, 356, 368, 370, 377, 431, 454, 480, 4...
5         [11, 62, 110, 141, 150, 260, 282, 316, 318, 35...
6         [1, 7, 17, 52, 62, 140, 141, 260, 494, 628, 64...
7         [11, 260, 348, 356, 364, 440, 480, 539, 553, 5...
8         [1, 3, 10, 21, 47, 48, 110, 150, 161, 207, 236...
9         [356, 858, 1923, 1997, 2706, 2841, 2959, 3798,...
10        [1, 11, 25, 260, 527, 858, 912, 969, 1136, 119...
11        [1, 32, 39, 110, 150, 158, 160, 165, 170, 172,...
12        [1, 34, 36, 104, 110, 260, 344, 356, 364, 380,...
13        [1, 11, 32, 47, 95, 110, 150, 160, 161, 185, 2...
14        [1, 17, 62, 150, 252, 260, 277, 314, 339, 356,...
15        [34, 150, 246, 356, 364, 457, 474, 515, 527, 5...
16        [39, 122, 356, 550, 587, 916, 934, 1197, 1265,...
17        [6, 110, 457, 1233, 1270, 1580, 1608, 1610, 20...
18        [186, 296, 318, 356, 527, 588, 608, 858, 912, ...
19        [1, 3, 6, 7, 14, 17, 61, 62, 74, 86, 88, 100, ...
20        [16, 111, 1080, 1208, 1221, 1291, 1884, 1994, ...
21        [6, 16, 32, 50, 111, 260, 262, 296, 318, 474, ...
22        [6, 16, 47, 50, 95, 110, 111, 165, 296, 318, 3...
23        [1, 25, 32, 47, 50, 110, 223, 293, 296, 318, 4...
24        [1, 6, 16, 18, 24, 25, 32, 34, 47, 50, 69, 73,...
25        [22, 39, 175, 223, 261, 296, 318, 337, 356, 37...
26        [21, 39, 47, 50, 110, 150, 288, 296, 300, 318,...
27        [11, 47, 104, 162, 231, 266, 368, 480, 553, 59...
28                      [213, 296, 356, 357, 410, 509, 555]
29        [9, 11, 15, 16, 20, 23, 31, 34, 47, 50, 60, 70...
30                     [596, 1061, 2238, 2324, 3147, 30707]
                                ...
138463     [21, 34, 150, 161, 296, 329, 349, 380, 457, 592]
138464    [1, 10, 107, 110, 260, 329, 364, 368, 457, 466...
138465      [318, 858, 3000, 5618, 6016, 6350, 7099, 31658]
138466    [233, 246, 265, 902, 1393, 1542, 1719, 1922, 1...
138467    [1, 11, 30, 32, 39, 47, 50, 70, 85, 112, 150, ...
138468    [50, 260, 318, 527, 858, 1221, 2571, 2959, 499...
138469    [348, 910, 912, 913, 1250, 2006, 2081, 4306, 5...
138470    [307, 308, 318, 527, 662, 837, 1635, 1653, 169...
138471    [1, 260, 318, 364, 500, 588, 595, 648, 747, 11...
138472    [32, 34, 47, 50, 223, 260, 296, 318, 356, 527,...
138473    [1, 32, 47, 70, 288, 296, 364, 551, 1025, 1089...
138474    [1, 2, 5, 6, 9, 10, 16, 19, 24, 25, 32, 47, 48...
138475    [246, 680, 750, 905, 912, 913, 922, 923, 946, ...
138476    [110, 253, 593, 1974, 3578, 4993, 5952, 7153, ...
138477    [260, 296, 527, 593, 608, 750, 825, 919, 920, ...
138478    [588, 741, 1042, 1200, 1214, 1274, 1584, 1747,...
138479    [196, 316, 480, 589, 748, 780, 1214, 1240, 152...
138480    [1, 32, 104, 135, 260, 648, 733, 736, 780, 784...
138481    [1, 50, 903, 1148, 1204, 1242, 1262, 1617, 167...
138482    [32, 50, 262, 648, 1197, 1407, 1704, 1717, 196...
138483    [1, 17, 25, 35, 36, 45, 50, 52, 58, 80, 111, 1...
138484    [3, 6, 11, 16, 21, 23, 36, 47, 50, 110, 150, 1...
138485    [858, 1221, 2329, 2571, 2959, 4993, 7153, 4851...
138486    [1, 70, 165, 231, 344, 356, 364, 367, 419, 441...
138487    [25, 39, 222, 223, 265, 446, 858, 866, 920, 10...
138489    [29, 50, 318, 593, 745, 858, 912, 1061, 1148, ...
138490    [17, 32, 34, 85, 110, 111, 123, 150, 199, 232,...
138491                       [1093, 2857, 3186, 4128, 6874]
138492    [58, 69, 246, 357, 441, 471, 858, 908, 1136, 1...
138493    [2, 18, 19, 70, 107, 150, 179, 202, 224, 235, ...
Length: 138287, dtype: object

In [20]:
df.rating

In [13]:
s = pd.Series([1,2,3,4])

In [14]:
s.tolist

0    1
1    2
2    3
3    4
dtype: int64